### ISSUE TITLE
Explanation 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/VIP-Parts#1]
We need to create a new simple app for AMSs for new market.
App should consist of 3-4 lines of fields, plus registration steps.

Registration steps should include: 
- Name 
- Address
- Phone 

App's field should include: 
- Vin Code field
- Part Code field
- Name of the part field
and 
- Send Button

**Comment by hasan5151** [comment]
only this 2 parts?

**Comment by AndroidAkyl** [comment]
Yes

**Comment by hasan5151** [comment]
what is the name of app?

**Comment by AndroidAkyl** [comment]
VIP

**Comment by hasan5151** [comment]
do we need db of users? or only we need orders

**Comment by AndroidAkyl** [comment]
we need both
